### ISSUE TITLE
2.0.0

### ISSUE THREAD

**Issue by kaelzhang** [kaelzhang/caviar#7]
## Tasks

- [x] **BREAKING** config chain: extend caviar into a business customized dev tool
- [ ] completes tests

### Unfinished tasks of 1.0.0

- Custom loader
  - [x] to load extra middlewares or plugins
  - [x] how to extend roe-scripts into a business customized dev tool

- Dependencies
  - [ ] why next build requires that client side should have `next-server` as a dependency?
  - [x] is it possible to disable `@babel/runtime-corejs2`
